<?php
/**
 * @file
 * Module to integrate with Auth0 to provision application and import keys generated into Apigee Edge.
 */

/**
 *
 */
 function auth0_app_flow_devconnect_developer_app_save(array $r, array &$form_state) {

     if ($form_state['complete form']['actions']['submit']['#value'] != "Create App") {
         return;
     }

    //dpm($r, "DEBUG");
    //dpm($form_state, "DEBUG");

    $app_displayname = $form_state['storage']['entity']->attributes['DisplayName'];
    $callback_url = $form_state['storage']['entity']->callbackUrl;

    $payload = '{
        "client_name": "' . $app_displayname .  '",
        "redirect_uris": ["'. $callback_url .'"],
        "token_endpoint_auth_method": "client_secret_post"
    }';

    $server_endpoint = variable_get('auth0_app_flow_server_endpoint', '')
    $authorization_header = variable_get('auth0_app_flow_authorization_header', '')

    $options = array(
        'method' => 'POST',
        'data' => $payload,
        'timeout' => 15,
        'headers' => array('Accept' => 'application/json', 'Content-Type' => 'application/json', 'Cache-Control' => 'no-cache', 'Authorization' => $authorization_header),
    );
    $result = drupal_http_request($server_endpoint, $options);

    //watchdog("auth0_app", "'Auth0 Result: ' . $result->data");

    $result = json_decode($result->data);


    global $user;
    $app_id = $r['data']['appId'];

    $app = new \Apigee\ManagementAPI\DeveloperApp(devconnect_default_org_config(), $user->mail);
    $app->loadByAppId($app_id);
    $old_key = $app->getConsumerKey();
    try {
        $app->createKey($result->client_id, $result->client_secret);
        $app->deleteKey($old_key);
    } catch (\Exception $e) {
        watchdog("auth0_app", "'Cannot create key: ' . $e->getMessage()");
        throw $e;
    }

    // drupal_set_message("<pre>" . print_r($result, 1) . "</pre>");
    return TRUE;
 }

/**
 * Implements hook_menu().
 */
function auth0_app_flow_menu() {
  $items['admin/config/administration/auth0_app_flow'] = array(
    'title' => 'Auth0 External Application Registration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('auth0_app_flow_configure'),
    // Use the default/standard site configuration permission.
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Creates/returns a form to configure the block's variables.
 *
 * @param array $form
 * @param array $form_state
 * @return array
 */
 function auth0_app_flow_configure($form, &$form_state) {
     $form['auth0_app_flow_server_endpoint'] = array(
        '#type' => 'textfield',
        '#title' => t('Auth0 Server Endpoint'),
        '#description' => t('The Auth0 server endpoint for your organization.'),
        '#default_value' => variable_get('auth0_app_flow_server_endpoint', 'https://organization.auth0.com/oidc/register'),
        '#size' => 60,
        '#maxlength' => 120,
        '#required' => TRUE,
     );
     
     $form['auth0_app_flow_authorization_header'] = array(
        '#type' => 'textfield',
        '#title' => t('Auth0 Authorization Token'),
        '#description' => t('The Auth0 Bearer Token for calling Auth0 APIs.'),
        '#default_value' => variable_get('auth0_app_flow_authorization_header', 'Bearer XYZ'),
        '#size' => 60,
        '#maxlength' => 10000,
        '#required' => TRUE,
     );
     return system_settings_form($form);
 }